#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sun Feb 16 23:24:39 2020

@author: kia
"""

"""
Project Euler 2

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

"""

a = 1
b = 2
counterO = 0
counterO = counterO + b
for i in range(1,50):
    print("Now in loop: " + str(i))
    c = a + b
    a = b
    b = c
    if c < 4000000:
        if c % 2 == 0:
            counterO = counterO + c
    else:
        break
print("Answer is: " + str(counterO))
    